server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MyDatabase?serverTimezone=GMT%2b8
    username: root
    password: 12345678

mybatis:
  #  扫描所有所有mybatis .xml文件
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
