server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.littlemonk.top:3306/MyDatabase?serverTimezone=GMT%2b8
    username: hammond
    password: 12345678

mybatis:
  #  扫描所有所有mybatis .xml文件
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: D:/毕业设计项目临时目录/files/